name: SDK / Unstable branch

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: unstable-branch

jobs:
  update:
    name: Update
    runs-on: ubuntu-24.04
    if: ${{ contains(github.repository_owner, 'jellyfin') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: master
          token: ${{ secrets.JF_BOT_TOKEN }}
      - name: Setup Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1
      - name: Run updateApiSpecUnstable task
        run: ./gradlew :openapi-generator:updateApiSpecUnstable
      - name: Run apiDump task
        run: ./gradlew apiDump
      - name: Commit changes
        if: always()
        run: |
          git config user.name jellyfin-bot
          git config user.email team@jellyfin.org
          git checkout -B openapi-unstable
          git add .
          git commit --allow-empty -m "Update OpenAPI to unstable"
          git push --force origin openapi-unstable
